---
- name: Apply compliance
  hosts: routers
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Gather interfaces
      ansible.netcommon.cli_command:
        command: show ip interface brief
      register: interfaces_output

    - name: Parse Ethernet interfaces
      set_fact:
        ethernet_interfaces: "{{ interfaces_output.stdout_lines | map('split') | selectattr(0, 'match', '^Ethernet[0-9]') | map(attribute=0) | list }}"

    - name: Debug parsed interfaces
      debug:
        var: ethernet_interfaces

    - name: Configure Ethernet interfaces
      ios_config:
        lines:
          - description Uplink to core switch
          - ip address 192.168.100.{{ item_index + 1 }} 255.255.255.0
          - no shutdown
        parents: "interface {{ item }}"
      loop: "{{ ethernet_interfaces }}"
      loop_control:
        index_var: item_index
      when: ethernet_interfaces | length > 0

    - name: Apply compliance template
      template:
        src: compliance_template.j2
        dest: /etc/network/configs/compliance.conf
      when: ethernet_interfaces | length > 0
