---
- name: Apply Compliance Template
  hosts: all
  gather_facts: no
  tasks:

    - name: Add host keys to known_hosts
      ansible.builtin.shell: "ssh-keyscan -H {{ inventory_hostname }} >> ~/.ssh/known_hosts"
      delegate_to: localhost

    - name: Gather network facts
      cisco.ios.ios_facts:
        gather_subset: all
      register: facts

    - name: Ensure Ethernet1/0 exists
      assert:
        that:
          - "'Ethernet1/0' in facts.ansible_facts.ios_interfaces"
        fail_msg: "Ethernet1/0 does not exist on {{ inventory_hostname }}"
      register: interface_check

    - name: Configure Ethernet interface Ethernet1/0
      when: interface_check is succeeded
      cisco.ios.ios_config:
        lines:
          - description Configured by Ansible
          - no shutdown
        parents: interface Ethernet1/0
      register: config_results

    - name: Revert Ethernet interface Ethernet1/0 settings
      when: interface_check is succeeded and config_results is failed
      cisco.ios.ios_config:
        lines:
          - shutdown
        parents: interface Ethernet1/0

    - name: Apply compliance template
      when: config_results is succeeded
      cisco.ios.ios_config:
        src: compliance_template.j2

    - name: Collect the final running configuration
      cisco.ios.ios_command:
        commands:
          - show running-config
      register: final_config

    - name: Save final configuration to file
      copy:
        content: "{{ final_config.stdout[0] }}"
        dest: "/path/to/save/config_{{ inventory_hostname }}.txt"
