---
- name: Apply compliance
  hosts: routers
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Gather interfaces
      ansible.netcommon.cli_command:
        command: show ip interface brief
      register: interfaces_output

    - name: Parse interface facts
      set_fact:
        ansible_net_interfaces: "{{ ansible_net_interfaces | default({}) | combine({ item[0]: item[1:] }) }}"
      loop: "{{ interfaces_output.stdout_lines | map('split') | selectattr(0, 'match', '^Ethernet[0-9]') | list }}"

    - name: Set Ethernet interface fact if present
      set_fact:
        ethernet_interfaces: "{{ ansible_net_interfaces.keys() | list }}"

    - name: Configure Ethernet interfaces
      ios_config:
        lines:
          - description Uplink to core switch
          - ip address 192.168.100.1 255.255.255.0
          - no shutdown
        parents: "interface {{ item }}"
      loop: "{{ ethernet_interfaces }}"
      when: ethernet_interfaces | length > 0

    - name: Apply compliance template
      template:
        src: compliance_template.j2
        dest: /etc/network/configs/compliance.conf
      when: ethernet_interfaces | length > 0
