---
- name: Apply compliance configuration
  hosts: all
  gather_facts: no
  tasks:

    - name: Gather network facts
      ansible.netcommon.cli_command:
        command: show ip interface brief
      register: interfaces_output

    - name: Ensure Ethernet1/0 exists
      set_fact:
        ethernet_interfaces: ["Ethernet1/0"]
      when: "'Ethernet1/0' in interfaces_output.stdout"

    - name: Configure Ethernet interface Ethernet1/0
      ansible.netcommon.cli_config:
        lines:
          - "interface Ethernet1/0"
          - "description Uplink to core switch"
          - "ip address 192.168.100.1 255.255.255.0"
          - "no shutdown"
      when: "'Ethernet1/0' in ethernet_interfaces"
      ignore_errors: yes
      register: config_results

    - name: Revert Ethernet interface Ethernet1/0 settings
      ansible.netcommon.cli_config:
        lines:
          - "interface Ethernet1/0"
          - "no description"
          - "no ip address"
      when: "'Ethernet1/0' in ethernet_interfaces and config_results is defined and config_results.failed"
      ignore_errors: yes
      register: revert_results

    - name: Apply compliance template
      ansible.builtin.template:
        src: compliance_template.j2
        dest: running-config.cfg
      when: config_results is defined and not config_results.failed

    - name: Collect the final running configuration
      ansible.netcommon.cli_command:
        command: show running-config
      register: running_config

    - name: Extract relevant network details
      set_fact:
        network_details: |
          Configured Interfaces: Ethernet1/0

          Reverted Interfaces: 
          {% if revert_results is defined %}
          Ethernet1/0
          {% else %}
          None
          {% endif %}

          Final Running Config:
          {{ running_config.stdout }}

    - name: Display relevant network details
      debug:
        var: network_details
