---
- name: Apply compliance
  hosts: routers
  gather_facts: yes
  connection: network_cli

  tasks:
    - name: Ensure ansible_net_interfaces fact is present
      ansible.netcommon.network_facts:
        gather_subset: interfaces

    - name: Set Ethernet interface fact if present
      set_fact:
        ethernet_interfaces: "{{ ansible_net_interfaces.keys() | select('match', '^Ethernet[0-9]') | list }}"
      when: ansible_net_interfaces is defined

    - name: Configure Ethernet interfaces
      ios_config:
        lines:
          - description Uplink to core switch
          - ip address 192.168.100.1 255.255.255.0
          - no shutdown
        parents: "interface {{ item }}"
      loop: "{{ ethernet_interfaces }}"
      when: ethernet_interfaces | length > 0

    - name: Apply compliance template
      template:
        src: compliance_template.j2
        dest: /etc/network/configs/compliance.conf
      when: ethernet_interfaces | length > 0
