---
- name: Collect facts from all devices and store as backup
  hosts: all
  gather_facts: no
  tasks:
    - name: Ensure SSH key is added to known hosts
      shell: ssh-keyscan -H {{ inventory_hostname }} >> ~/.ssh/known_hosts
      delegate_to: localhost
      changed_when: False

    - name: Gather network facts
      ansible.netcommon.network_cli:
        provider:
          host: "{{ inventory_hostname }}"
          username: "your_username"
          password: "your_password"
          authorize: yes
          auth_pass: "your_enable_password"
      register: facts

    - name: Store facts to a file
      copy:
        content: "{{ facts }}"
        dest: "/path/to/store/facts/{{ inventory_hostname }}_facts.json"
