- name: Collect facts from all devices and store as backup
  hosts: all
  tasks:
    - name: Ensure SSH key is added to known hosts
      local_action: shell ssh-keyscan -H {{ inventory_hostname }} >> ~/.ssh/known_hosts
      run_once: true

    - name: Gather network facts
      ansible.netcommon.network_cli:
        provider: "{{ cli }}"
      register: gather_facts_output

    - name: Store facts to a file
      copy:
        content: "{{ gather_facts_output }}"
        dest: "/path/to/backup/{{ inventory_hostname }}_facts.json"
