- name: Network Backup and Compliance Check
  hosts: routers
  gather_facts: no
  tasks:
    - name: Ensure the /tmp/backups directory exists
      file:
        path: /tmp/backups
        state: directory
        mode: '0755'

    - name: Backup running configuration
      ios_command:
        commands:
          - show running-config
      register: running_config

    - name: Save running config to file
      copy:
        content: "{{ running_config.stdout[0] }}"
        dest: "/tmp/backups/{{ inventory_hostname }}_running_config.txt"

    - name: Load compliance template
      template:
        src: compliance_template.j2
        dest: "/tmp/{{ inventory_hostname }}_compliance.txt"

    - name: Compare running config with compliance template
      shell: diff /tmp/backups/{{ inventory_hostname }}_running_config.txt /tmp/{{ inventory_hostname }}_compliance.txt
      register: diff_output
      ignore_errors: yes

    - name: Report compliance status
      debug:
        msg: "Compliance check for {{ inventory_hostname }}: {{ diff_output.stdout }}"

    - name: Remediate non-compliance (optional)
      ios_config:
        src: /tmp/{{ inventory_hostname }}_compliance.txt
      when: diff_output.rc != 0
