- name: Configure banner on routers
  hosts: routers
  gather_facts: no
  tasks:
    - name: Set banner
      ios_config:
        lines:
          - banner login ^C
          - Welcome to the router! Unauthorized access is prohibited.^C
        provider:
          username: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          host: "{{ ansible_host }}"
