- name: Apply configuration change to routers
  hosts: routers
  gather_facts: no
  tasks:
    - name: Set login banner
      ios_command:
        commands:
          - configure terminal
          - banner login ^C
          - Welcome to the router! Unauthorized access is prohibited.^C
          - end
