- name: Apply configuration change to routers
  hosts: routers
  gather_facts: no
  tasks:
    - name: Set MOTD banner
      ios_command:
        commands:
          - configure terminal
          - banner motd $ Attention! We will be having scheduled system maintenance on this device. $
          - end
      vars:
        ansible_command_timeout: 120
